name: Deploy to Firebase Hosting on merge
on:
    push:
        branches:
            - main

permissions:
    checks: write
    contents: read
    pull-requests: write

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout del repositorio
              uses: actions/checkout@v5 # Actualizado a v5

            - name: Configurar Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20 # O 22 si prefieres

            - name: Instalar y Compilar
              run: |
                  npm install --legacy-peer-deps
                  npm run build

            - name: Desplegar a Firebase
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_OMS_ECOMMERCE }}
                  channelId: live
                  projectId: oms-ecommerce
